runtime: php
env: flex

runtime_config:
  document_root: gcp-php-mysql
   front_controller_file: index.php

handlers:
  -url: /css
  dynamic_dir: css
env_variables:
  MYSQL_Host: mysql:unix_socket=/cloudsql/surajsojas:us-west2:sojassukant
  MYSQL_DB: cloud
  MUSQL_USER: sojas
  MYSQL_PASS: 123456

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
