runtime: php
env: flex

runtime_config:
  document_root: web



env_variables:
 APP_LOG: errorlog
 GOOGLE_BUCKET_NAME: "us.artifacts.surajsojas.appspot.com"
 MYSQL_USER: sojas
 MYSQL_PASSWORD: sojassukant
 MYSQL_DSN: mysql:dbname=maezoz;unix_socket=/cloudsql/surajsojas:us-west2:sojassukant
beta_settings:
  cloud_sql_instances: "surajsojas:us-west2:sojassukant"

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/php/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
